### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [ukBaz/BLE_GATT#10]
This is my script:
```
import BLE_GATT

ubit_address = 'BE:58:4A:00:37:8B'
led_text = '0000fff0-0000-1000-8000-00805f9b34fb'


ubit = BLE_GATT.Central(ubit_address)
ubit.connect()
ubit.char_write(led_text, b'7e070503000000ffef')
ubit.disconnect()
```

When I run it, I get this error:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\send_data.py", line 1, in <module>
    import BLE_GATT
  File "C:\python\lib\site-packages\BLE_GATT\__init__.py", line 2, in <module>
    from .central import Central
  File "C:\python\lib\site-packages\BLE_GATT\central.py", line 4, in <module>
    from pydbus import SystemBus
  File "C:\python\lib\site-packages\pydbus\__init__.py", line 1, in <module>
    from .bus import SystemBus, SessionBus, connect
  File "C:\python\lib\site-packages\pydbus\bus.py", line 1, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'
```
I tried installing dependencies from setup.py but it still gives me this error.

**Comment by ukBaz** [comment]
It looks like you are running this on Windows. Apologies, it should have been clearer that this package only runs on Linux.

You might want to look at something like [Bleak](https://pypi.org/project/bleak/) that is well supported on Windows.

**Comment by Andrei-Iosifescu123** [comment]
I will try Bleak. Thank you
