### ISSUE TITLE
error install vext.gi

### ISSUE THREAD

**Issue by SatriyoJati** [ukBaz/BLE_GATT#12]
python3 version : 3.9.2
Operating System: Raspbian GNU/Linux 11 (bullseye)
Kernel: Linux 5.15.84-v7l+
Architecture: arm

I am not using virtual environment to instsall BLE_GATT, I got error an when installing using pip3 : 
```none
 Building wheels for collected packages: vext.gi
  Building wheel for vext.gi (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      /home/pi/.local/lib/python3.9/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      /home/pi/.local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-armv7l/wheel
      running install
      vext.gi Install
      Not installing PTH file to real prefix
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-37vfvsuz/vext-gi_80a1ad7675094391bb96c8ca0557d558/setup.py", line 62, in <module>
          setup(
        File "/home/pi/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/pi/.local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/pi/.local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/pi/.local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/pi/.local/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/pi/.local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 275, in run
          self.egg2dist(self.egginfo_dir, distinfo_dir)
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 372, in egg2dist
          raise ValueError(err)
      ValueError: Egg metadata expected at build/bdist.linux-armv7l/wheel/vext.gi-0.7.4-py3.9.egg-info but not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vext.gi
  Running setup.py clean for vext.gi
Failed to build vext.gi
ERROR: Could not build wheels for vext.gi, which is required to install pyproject.toml-based projects
```
how to install the library without virtual environment?

**Comment by ukBaz** [comment]
You haven't shown early enough in your install what commands you are using. I'm assuming that you have done:
```none
$ python3 -m venv venv_ble
$ . venv_ble/bin/activate
$ pip3 install BLE_GATT
```
And that is when you are seeing the error?

Try upgrading your version of `pip` by using:
```none
$ pip3 install pip --upgrade
```
If that doesn't work then please show what commands you are using to create the Python virtual environment and pip install commands.

**Comment by ukBaz** [comment]
Closed due to lack of activity. Please update the issue if there is still an issue

**Comment by profff** [comment]
I have the same issue under windows 11
I'm NOT using virtual env just try to install in regular env 
I've try with pip pip3 I've try also to upgrade
```
PS D:\dev\TPMS_MK3\TOOLS\BLE_PC> pip3 install BLE_GATT
Collecting BLE_GATT
  Using cached BLE_GATT-0.5.0-py2.py3-none-any.whl.metadata (13 kB)
Collecting pydbus (from BLE_GATT)
  Using cached pydbus-0.6.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting vext.gi (from BLE_GATT)
  Using cached vext.gi-0.7.4.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... done
Collecting vext>=0.7.4 (from vext.gi->BLE_GATT)
  Using cached vext-0.7.6-py3-none-any.whl
Collecting ruamel.yaml>=0.11.10 (from vext>=0.7.4->vext.gi->BLE_GATT)
  Using cached ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.11.10->vext>=0.7.4->vext.gi->BLE_GATT)
  Using cached ruamel.yaml.clib-0.2.12-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Using cached BLE_GATT-0.5.0-py2.py3-none-any.whl (8.4 kB)
Using cached pydbus-0.6.0-py2.py3-none-any.whl (19 kB)
Using cached ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
Using cached ruamel.yaml.clib-0.2.12-cp312-cp312-win_amd64.whl (115 kB)
Building wheels for collected packages: vext.gi
  Building wheel for vext.gi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      C:\Users\o.gaste\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      C:\Users\o.gaste\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      vext.gi Install
      running install_data
      creating build
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\vext.gi-0.7.4.data
      creating build\bdist.win-amd64\wheel\vext.gi-0.7.4.data\data
      creating build\bdist.win-amd64\wheel\vext.gi-0.7.4.data\data\share
      creating build\bdist.win-amd64\wheel\vext.gi-0.7.4.data\data\share\vext
      creating build\bdist.win-amd64\wheel\vext.gi-0.7.4.data\data\share\vext\specs
      copying gi.vext -> build\bdist.win-amd64\wheel\vext.gi-0.7.4.data\data\share\vext\specs
      running install_egg_info
      running egg_info
      writing vext.gi.egg-info\PKG-INFO
      writing dependency_links to vext.gi.egg-info\dependency_links.txt
      writing requirements to vext.gi.egg-info\requires.txt
      writing top-level names to vext.gi.egg-info\top_level.txt
      reading manifest file 'vext.gi.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.txt'
      writing manifest file 'vext.gi.egg-info\SOURCES.txt'
      Copying vext.gi.egg-info to build\bdist.win-amd64\wheel\.\vext.gi-0.7.4-py3.12.egg-info
      running install_scripts
      Install vext files:
      error: [WinError 2] Le fichier spécifié est introuvable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vext.gi
  Running setup.py clean for vext.gi
Failed to build vext.gi
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (vext.gi)
```
 
in error message it propose to `--use-pep517 ` but result is the same

**Comment by ukBaz** [comment]
@profff Please don't post on a closed issue especially as yours is a different issue because you are running on Windows 11. This library will only run on Linux so that is the issue with your install.
